# Generated by Django 3.1.4 on 2021-02-14 13:48

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'max_length': 'ユーザー名の文字数の上限は150です', 'unique': 'そのユーザー名は既に使用されています'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='ユーザー名に使用できるの記号は@/./+/-/_のみです')])),
            ],
        ),
        migrations.CreateModel(
            name='UserOnGoogle',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Google ID')),
                ('email', models.CharField(error_messages={'unique': 'そのメールアドレスは既に使用されています'}, max_length=300, unique=True, validators=[django.core.validators.EmailValidator('メールアドレスの形式が不正です')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.username')),
            ],
        ),
        migrations.CreateModel(
            name='UserOnMyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(error_messages={'unique': 'そのメールアドレスは既に使用されています'}, max_length=300, unique=True, validators=[django.core.validators.EmailValidator('メールアドレスの形式が不正です')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.username')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
