# Generated by Django 3.1.4 on 2021-03-05 11:15

from django.db import migrations, models
import django.db.models.deletion
import validators.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210304_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateChatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_introduction', models.CharField(blank=True, max_length=256)),
                ('icon', models.ImageField(default='uploads/DefaultIconImage.png', upload_to='uploads/', validators=[validators.image.MaxFileSizeValidator(52428800), validators.image.ImageAspectRatioValidator(validators.image.WidthHeight(1, 1))])),
                ('cover_image', models.ImageField(default='uploads/DefaultCoverImage.png', upload_to='uploads/', validators=[validators.image.MaxFileSizeValidator(52428800), validators.image.ImageAspectRatioValidator(validators.image.WidthHeight(height=1, width=3))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.username')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChatroomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enter', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('GU', 'Guest'), ('MA', 'Manager'), ('OW', 'Owner')], default='GU', max_length=2)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.privatechatroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(error_messages={'max_length': 'メッセージの文字数の上限は2048です'}, max_length=2048)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.privatechatroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatroomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enter', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('GU', 'Guest'), ('MA', 'Manager'), ('OW', 'Owner')], default='GU', max_length=2)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.chatroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(error_messages={'max_length': 'メッセージの文字数の上限は2048です'}, max_length=2048)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.chatroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
