# Generated by Django 3.1.4 on 2021-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='room_name',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
