# Generated by Django 3.1.4 on 2021-02-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatroomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enter', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('GU', 'Guest'), ('MA', 'Manager'), ('OW', 'Owner')], default='GU', max_length=2)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.privatechatroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(error_messages={'max_length': 'メッセージの文字数の上限は2048です'}, max_length=2048)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.privatechatroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
