# Generated by Django 3.1.4 on 2021-02-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_privatechatmessage_privatechatroommember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='password',
        ),
    ]
