# Generated by Django 3.1.4 on 2021-02-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chatapp', '0003_remove_privatechatroom_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_introduction', models.CharField(max_length=256)),
                ('icon', models.ImageField(upload_to='uploads/')),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.username')),
            ],
        ),
    ]
