# Generated by Django 3.1.4 on 2021-02-23 10:53

import chatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/', validators=[chatapp.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(upload_to='uploads/', validators=[chatapp.models.validate_image]),
        ),
    ]
